# sacado de https://github.com/appropriate/docker-postgis
FROM mdillon/postgis
MAINTAINER Mike Dillon <mike@appropriate.io>

# docker run --name postgres-infonavit -e POSTGRES_PASSWORD=infonavit -e POSTGRES_USER=infonavit -e POSTGRES_DB=infonavit -p 5433:5432 -d mdillon/postgis
